### PR TITLE
Project layout

### PR DESCRIPTION
**Pull request by tierriminator**
This PR adjusts the project layout, such that the `src` and `test` directory are top-level directories.
Additionally, the sources are packaged in a `idpi` package in the `src` directory.

### CODE REVIEW

**Review by cosunae — APPROVED** [review]
looks good to me

**Comment by cosunae** [comment]
launch jenkins

**Review by cosunae — CHANGES_REQUESTED** [review]
Can you take a look at the jenkins tests ? 
I guess the tests require some adaptation

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Comment by tierriminator** [comment]
launch jenkins

**Pull request closed without merging**
